services:

  bot: 
    build: .
    depends_on:
      - mongodb
    env_file: .env
    restart: on-failure
    volumes:
      - type: bind
        source: ./config.json
        target: /app/config.json
      - type: bind
        source: ./json/auto
        target: /app/json/auto
    
  mongodb:
    image: mongo:8.0-noble
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    volumes:
      - type: bind
        source: ./dbdata
        target: /data/db

  cloudflared:
    image: erisamoe/cloudflared
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - bot